variable "environment" {}
variable "instance_type" {}
variable "cidr_blocks" {}
variable "app_cidr_blocks" {}
variable "application" {}
variable "customer" {}
variable "s3_bucket" {}
variable "instance_count" {}
variable "zone_id" {}
variable "private_key" {}
variable "key_name" {}